id: QmQUQyVo2Z1AzrgtjEwkkQLomCpHgQTxDRpthS4BbMYX14
name: luciverse-sovereign
description: Sovereign Identity, Asset, Financial Engine + AI Inference for d8rth
notification:
    email: daryl@lucidigital.net
